services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: tsunagaki-backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: mysql
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true
    networks:
      - tsunagaki-network

  nginx:
    image: nginx:1.25.3-alpine
    container_name: tsunagaki-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - tsunagaki-network

  mysql:
    image: mysql:8.0.36
    container_name: tsunagaki-mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tsunagaki-network

  redis:
    image: redis:7.2-alpine
    container_name: tsunagaki-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - tsunagaki-network

  websocket:
    build:
      context: .
      dockerfile: docker/websocket/Dockerfile
    container_name: tsunagaki-websocket
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./websocket:/app
      - /app/node_modules
    ports:
      - "${WEBSOCKET_PORT}:6001"
    depends_on:
      - redis
    tty: true
    stdin_open: true
    networks:
      - tsunagaki-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: tsunagaki-phpmyadmin
    restart: always
    ports:
      - "${PHP_MYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - tsunagaki-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: tsunagaki-swagger
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - ./documents/tsunagaki.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    networks:
      - tsunagaki-network

volumes:
  db_data:

networks:
  tsunagaki-network:
    driver: bridge
